### ISSUE TITLE
media keys sending

### ISSUE THREAD

**Issue by impoetk** [girst/hardpass-passwordmanager#7]
first of all, awesome stuff there ;)

im trying to implement an usb media controller. rotary encoder in the pi zero to control volume an reproduction of media

im able to send normal keys, shift keys and stuff, but media keys don't seem to be working, i stumbled upon something like keycodes above 101 need a special descriptor.... or something like that

can you point me maybe in some documentation how to achieve this?

Thanks in advance

**Comment by girst** [comment]
sorry, don't know about that. it's been a while since i looked at the 
project, but i think send_hid uses the "boot" protocol, which is the 
easiest to implement and use. you might find what you're looking for in 
the usb hid spec 
(https://www.usb.org/sites/default/files/documents/hut1_12v2.pdf), or 
this wiki page (https://github.com/ckuethe/usbarmory/wiki/USB-Gadgets), 
but no promises ;-)
